name: GitHub Readme YouTube Cards
on:
  schedule:
    # Fire at 10:15 AM on the 15th day of every month
    - cron: 0 15 10 15 * ?
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCEWoKMFHVgyzI1u7n1wlCzw
